"""Generate architecture documentation and SVG from persisted benchmark data."""

from __future__ import annotations

import html
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.db.session import SessionLocal
from app.metrics import metrics_snapshot

DOCS_DIR = ROOT.parent / "docs"
LAYERS = [
    ("embedding_ms", "Embedding"),
    ("faiss_ms", "FAISS retrieval"),
    ("sql_ms", "Structured SQL"),
    ("graph_ms", "Graph retrieval"),
    ("llm_ms", "LLM synthesis"),
]


def _value(snapshot: dict, field: str, percentile: str) -> float:
    return float(snapshot.get("percentiles", {}).get(field, {}).get(percentile, 0.0) or 0.0)


def render(snapshot: dict) -> tuple[str, str]:
    count = int(snapshot.get("sample_count", 0))
    labels = [
        f"{label} p50 {_value(snapshot, field, 'p50'):.1f} ms / p95 {_value(snapshot, field, 'p95'):.1f} ms"
        for field, label in LAYERS
        if _value(snapshot, field, "p50") > 0 or _value(snapshot, field, "p95") > 0
    ]
    if not labels:
        labels = ["No benchmark samples recorded yet"]
    total_p50 = _value(snapshot, "total_ms", "p50")
    total_p95 = _value(snapshot, "total_ms", "p95")
    markdown = """# FloatChat architecture

This diagram is generated by `backend/scripts/generate_architecture.py` from
durable `benchmark_runs` samples. Values are measured wall-clock percentiles,
not estimates.

```mermaid
flowchart LR
"""
    nodes = []
    for index, label in enumerate(labels):
        node = chr(ord("A") + index)
        nodes.append(f"    {node}[{label.replace('/', ' / ')}]")
    markdown += " --> ".join(nodes) + "\n```\n\n"
    markdown += f"Samples: {count}. Total latency: p50 {total_p50:.1f} ms, p95 {total_p95:.1f} ms.\n"
    markdown += "\nThe live `/metrics` endpoint exposes the same layer percentiles and recent runs.\n"

    width = 220 * len(labels)
    svg_parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="180" viewBox="0 0 {width} 180">',
        '<rect width="100%" height="100%" fill="#020b13"/>',
        '<text x="20" y="28" fill="#c8f7ff" font-family="Arial" font-size="16">FloatChat measured query pipeline</text>',
    ]
    for index, label in enumerate(labels):
        x = 20 + index * 220
        svg_parts.append(f'<rect x="{x}" y="55" width="190" height="70" rx="12" fill="#0d2635" stroke="#45d9ee"/>')
        safe = html.escape(label)
        svg_parts.append(f'<text x="{x + 10}" y="82" fill="#d8f8ff" font-family="Arial" font-size="11">{safe[:28]}</text>')
        svg_parts.append(f'<text x="{x + 10}" y="101" fill="#9fb8c4" font-family="Arial" font-size="10">{safe[28:56]}</text>')
        if index < len(labels) - 1:
            svg_parts.append(f'<path d="M{x + 190} 90 H{x + 215}" stroke="#45d9ee" marker-end="url(#arrow)"/>')
    svg_parts.insert(2, '<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3 z" fill="#45d9ee"/></marker></defs>')
    svg_parts.append(f'<text x="20" y="155" fill="#f7c66b" font-family="Arial" font-size="11">total p50 {total_p50:.1f} ms · p95 {total_p95:.1f} ms · {count} samples</text>')
    svg_parts.append("</svg>")
    return markdown, "\n".join(svg_parts)


def main() -> None:
    with SessionLocal() as db:
        snapshot = metrics_snapshot(db)
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    markdown, svg = render(snapshot)
    (DOCS_DIR / "architecture.md").write_text(markdown, encoding="utf-8")
    (DOCS_DIR / "architecture.svg").write_text(svg, encoding="utf-8")
    print(f"Generated architecture docs from {snapshot['sample_count']} samples.")


if __name__ == "__main__":
    main()
